channels:
- currentCSV: ibm-monitoring-grafana-operator.v1.10.2
  name: stable-v1
- currentCSV: ibm-monitoring-grafana-operator.v1.11.1
  name: beta
- currentCSV: ibm-monitoring-grafana-operator.v1.12.0
  name: dev
- currentCSV: ibm-monitoring-grafana-operator.v1.11.1
  name: v3
defaultChannel: stable-v1
packageName: ibm-monitoring-grafana-operator-app
