channels:
- currentCSV: ibm-monitoring-grafana-operator.v1.9.1
  name: stable-v1
- currentCSV: ibm-monitoring-grafana-operator.v1.9.1
  name: beta
- currentCSV: ibm-monitoring-grafana-operator.v1.9.2
  name: dev
defaultChannel: stable-v1
packageName: ibm-monitoring-grafana-operator-app
