apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "Grafana",
          "metadata": {
            "name": "ibm-monitoring"
          },
          "spec": {
            "baseImage": "quay.io/opencloudio/grafana",
            "baseImageTag": "v6.5.2-build.2",
            "routerImage": "quay.io/opencloudio/icp-management-ingress",
            "routerImageTag": "2.5.1",
            "dashboardCtlImage": "quay.io/opencloudio/dashboard-controller",
            "dashboardCtlImageTag": "v1.2.0-build.3",
            "initImage": "quay.io/opencloudio/icp-initcontainer",
            "initImageTag": "1.0.0-build.3",
            "imagePullSecrets": [
              "infra-registry-key"
            ],
            "ipVersion": "4",
            "isHub": false,
            "resources": {
              "dashboard": 1,
              "grafana": 2,
              "router": 1
            },
            "service": {
              "ports": [
                {
                  "name": "ibm-monitoring-grafana",
                  "port": 3000,
                  "protocol": "TCP"
                }
              ]
            },
            "tlsClientSecretName": "ibm-monitoring-client-certs",
            "tlsSecretName": "ibm-monitoring-certs",
            "prometheusServiceName": "ibm-monitoring-prometheus",
            "prometheusServicePort": 9090
          }
        },
        {
          "apiVersion": "monitoringcontroller.cloud.ibm.com/v1",
          "kind": "MonitoringDashboard",
          "metadata":{
            "name": "sample-dashboard"
          },
          "spec": {
            "enabled": true,
            "data":
              {
                "id": "abc",
                "uid": "123456",
                "title": "Marco Test Dashboard",
                "tags": [ "test" ],
                "timezone": "browser",
                "schemaVersion": 16,
                "version": 1
              }
            }
        },
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "OperandRequest",
          "metadata": {
            "name": "monitoring-grafana-operator-request"
          },
          "spec": {
            "requests": [
              {
                "operands": [
                  {
                    "name": "ibm-iam-operator",
                  },
                  {
                    "name": "ibm-management-ingress-operator",
                  },
                  {
                    "name": "ibm-commonui-operator"
                  }
                ],
                "registry":"common-service"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring
    certified: 'false'
    createdAt: 2020-04-25 12:00:00
    support: IBM
    description: Provisions node-exporter, kube-state-metrics and collectd exporter with tls enabled
    repository: https://github.com/IBM/ibm-monitoring-grafana-operator
    containerImage: quay.io/opencloudio/ibm-monitoring-grafana-operator
  name: ibm-monitoring-grafana-operator.v1.8.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Grafana is the Schema for the grafanas API
      kind: Grafana
      name: grafanas.operator.ibm.com
      version: v1alpha1
      displayName: IBM Monitoring Grafana
      resources:
      - kind: deployments
        name: A Kubernetes Deployment
        version: v1
      - kind: services
        name: A Kubernetes Service
        version: v1
      - kind: servicemonitors
        name: A Kubernetes Servicemonitor
        version: v1
      - kind: ingresses
        name: A Kubernetes Ingress
        version: v1beta1
      - kind: pods
        name: A Kubernetes Pod
        version: v1
      - kind: configmaps
        name: A Kubernetes Configmap
        version: v1
      specDescriptors:
      - description: grafana spec define initImage as initial image
        displayName: Initial Image
        path: initImage
      - description: grafana spec defines initImageTag as initial image tag
        displayName: Initial Image Tag
        path: initImageTag
      - description: baseImage as grafana base image
        displayName: Base Image
        path: baseImage
      - description: baseImagetag as grafana base image tag
        displayName: Base Image Tag
        path: baseImageTag
      - description: dashboardCtlImage as dashbord controller image
        displayName: Dashboard Controller Image
        path: dashboardCtlImage
      - description: dashboardCtlImageTag as dashboard controller image tag
        displayName: Dashboard Controller Image Tag
        path: dashboardCtlImageTag
      - description: imagePullSecrets as images pull secrets
        displayName: Image Pull Secrets
        path: imagePullSecrets
      - description: ipVersion as IP version, IPv4 or IPv6
        displayName: IP Version
        path: ipVersion
      - description: isHub as it is hub cluster or not.
        displayName: IS HUB
        path: isHub
      - description: prometheusServiceName as prometheus service name
        displayName: Prometheus Service Name
        path: prometheusServiceName
      - description: prometheusServicePort as prometheus service port
        displayName: Prometheus Service Port
        path: prometheusServicePort
      - description: resources as time of the base resource unit of components
        displayName: Resources
        path: resources
      - description: routerImage as router image
        displayName: Router Image
        path: routerImage
      - description: routerImageTag as router image tag
        displayName: Router Image Tag
        path: routerImageTag
      - description: tlsClientSecretName as TLS client secret name
        displayName: TLS Client Secret Name
        path: tlsClientSecretName
      - description: tlsSecretName as TLS secret name
        displayName: TLS Secret Name
        path: tlsSecretName
      - description: service as grafana service
        displayName: Service
        path: service
    - description: MonitoringDashboard is the Schema for Grafana Dashboard
      kind: MonitoringDashboard
      name: monitoringdashboards.monitoringcontroller.cloud.ibm.com
      version: v1
      displayName: IBM Grafana Dashboard
  description: Grafana Operator for IBM common service monitoring stack
  displayName: IBM Grafana Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAFiUlEQVRYhb1Xa2wUVRT+zp25M9vtY1soUtBaWkCKhaJpgihqICa8I1JBkUrkIY2CPBMICf6ASIwEBdFaU3lopC1ExWCAGEQiBGiwCiYNj/KoUCtQQi19bem+7vEHu2V2uruUxniSk+ye+53v+869M7OzhB4GzxngaPLFbSUFb4cul6TtrHL3hEf0SHwtRLPXsZeYXwfxPIfyfsdjxuj/m4GWS0PfBjD+niNMaOl/Y2FPuOhBG5pn5PRiqSoBHmgjus7MxQw6nuyvPn4jJc+Md7tfYkYOBO1JLj1/+oEM1M/Oje/b0O6nHy97AKBx9tBhIqDeBSgfgLzPWPUAAEZasLInubx6+n0N3J41ZClBzAJ4BAAzWL4AUBXA0wD06JwBqkkuPz8o0koYIYGWApxpwwwBeEgU5hYA5wBcBygA5j4QyLZMHgz2RbNmn6g1GtASisFlLLStKZ5zFfQtAnZAY0H2cI1pPoMXAHACyL79WvaKlF3Vm+xY2xFklxJQEEP8KkG96iq/WNkNo/hn5rB0TQRKAJ4IIKCEGNur9NwxKyb8NiQcik7HdT7Fo7srDgC9d5+pc5WfnwzwBgCaYC7hwrywCzjMgN/k76FxIzSGLf2QNK3P7gvXuyseCgI4ufzCauj8OYQa2tzRmm9bD4/muY8tB8F+VsWuHRcXRRJomjdoHEEUgJEHAgG4AeA4KFDq2l5zOYTjGTlGS4LvNAh1rh0XJ0Y3UDhoEQhFlpJSeiAr5bMrtVZcY2GWSyNRCmBKlOH9AEqSnB0rafPfdwCgZcHAZ1jQUY9mpjxUfLYNiPAoFgaPJsmw5DG7OBfmSd2gAyR5yl0MGknyUTK4iiRzsE8nyYtafY4jjYVZLgBI2lpTAclHTPLmdOrZDbDBo2AwQkkSP9sxrQmNS2HwaBjsZakWJ3pdaUlFNWOSPq0ZoRz+gTD5y3scaqSegHIO7bapvham/9EuBhigllUZ80mqTJIKoWTTf7bLLkleSFKB9MBy1+YrRfTFqc4HTfKHtVeSPvpzHgy12sIzqW1V5ssA4NWMvQGhfg/hCQB4bY7R5m/bBSDfLsaknk96r67z3nWvTe+v/OIaA7WJ62szCWB7T2igtjUZh0EYGyydSFxf+2yXYQCgDa1bSHK+7exBkqHpIsHaoEDJJBlC51+iiQcnYzKxzcL1dOv7aX26GHB/kD6VDPUWpEKkZF09bm1IiPfUQio/S+WKJh4KTVKFhUuA9Bw7RkBX68hgRE1TvRA22cqbbjLVPuHg8e2bHnk4lgHSApqVSxicYMcINgJl0aYP5rg7Rf0ywppMXg5dNbAW2N/yaf/sUP3WhtREK06Z/lwrF+kq7CUGAETCkvqNpKuZJLkh0jVAkjUW6mNrU9w7N2qFg54jyTW6ps60F6edbi9OO+lM1FaFsRs8y8oFyRvbi/o+FbZLoQ+8PTWxQ4llDBQA1PX3n2ix8836InuZS3slue/oA3y696+UuU1NoXr7trSRYD6Jrk/bfc4FN1/sYsAa7q9S8wREBcCGVYuZV8TNadhCFP3qB4A72/plQPcfA5AeYfly3Jxbg0NfIr4Vx89pOAXJ63B320JJZGBzR3nqT+6y1Lxo4p6y3lPh9J2A5HRLbzN0PgCJNV6nJ/IR2IO/geah1P0AT4gC+QOEEwCqocgH4iwAkwAMt+EUiCc5pjcejEQS9SWTXkHA80OgIcZmPxnMmMHMyxzTmiKKxzRwd5Vz7ycQI3wEzDcnN+2MKRFrkSSrnuvTJWNcbPFuGFBXGXjCUvqNFK+GYAEWuUw0mMEDCMgEEH7rEh3pjs3YR2CqEmJRw6yusY7D5ih3lWW18z2BD/aN9ye694MxJljyBBifdMfAfxbMEP5f49/wVToPeSud3f6j+i+d81sWOOKIUgAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          - nodes
          - nodes/proxy
          - endpoints
          - pods
          - configmaps
          - namespaces
          verbs:
          - get
          - list
          - watch
        - nonResourceURLs:
          - /metrics
          verbs:
          - get
        - apiGroups:
          - monitoringcontroller.cloud.ibm.com
          resources:
          - monitoringdashboards
          verbs:
          - '*'
        serviceAccountName: ibm-monitoring-grafana
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - certificates
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - clusterissuers
          verbs:
          - use
        - apiGroups:
          - operator.ibm.com
          resources:
          - grafanas
          - grafanas/finalizers
          - grafanas/status
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - monitoringcontroller.cloud.ibm.com
          resources:
          - monitoringdashboards
          verbs:
          - '*'
        serviceAccountName: ibm-monitoring-grafana-operator
      deployments:
      - name: ibm-monitoring-grafana-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-monitoring-grafana-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-monitoring-grafana-operator
              annotations:
                productName: IBM Cloud Platform Common Services
                productID: "068a62892a1e4db39641342e592daa25"
                productVersion: "3.3.0"
                productMetric: FREE
            spec:
              containers:
              - command:
                - ibm-grafana-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-monitoring-grafana-operator
                image: quay.io/opencloudio/ibm-monitoring-grafana-operator
                imagePullPolicy: Always
                name: grafana
                resources: {}
              serviceAccountName: ibm-monitoring-grafana-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  links:
  - name: IBM Monitoring Grafana Operator
    url: https://github.com/IBM/ibm-monitoring-grafana-operator
  maintainers:
  - email: dongdwdw@cn.ibm.com
    name: Dong Wang
  provider:
    name: IBM
  replaces: ibm-monitoring-grafana-operator.v1.8.0
  version: 1.8.1
