apiVersion: operator.ibm.com/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
spec:
  service:
    type: NodePort
    ports:
      - name: grafana-service
        protocol: TCP
        port: 3000
  resources:
    grafana: 2
    router: 1
    dashboard: 1
  baseImage: hyc-cloud-private-release-docker-local.artifactory.swg-devops.com/ibmcom-amd64/grafana
  tag: v6.5.2-build.1
  ipVersion: "4"
  isHub: false
